# Copyright The mirrorshades Contributors.
# SPDX-License-Identifier: Apache-2.0

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: check-shebang-scripts-are-executable
    -   id: check-symlinks
    -   id: check-toml
    -   id: check-vcs-permalinks
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: trailing-whitespace
-   repo: https://github.com/fsfe/reuse-tool
    rev: v6.2.0
    hooks:
    -   id: reuse
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.5.1
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
    -   id: flake8
-   repo: https://github.com/pycqa/isort
    rev: 9.0.1
    hooks:
    -   id: isort
-   repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.39
    hooks:
        - id: pymarkdown
