#! /usr/bin/env python3
# Copyright (c) 2020-2021 Paul Barker <paul@pbarker.dev>
# SPDX-License-Identifier: Apache-2.0

import sys
from os.path import dirname, join

src_path = join(dirname(__file__), "src")
sys.path.insert(0, src_path)

from mirrorshades.__main__ import main  # noqa: E402

main()
