#! /usr/bin/env python3
# Copyright (c) 2020-2021 Paul Barker <paul@pbarker.dev>
# SPDX-License-Identifier: Apache-2.0

import sys
from os.path import dirname, join

src_path = join(dirname(__file__), "src")
sys.path.insert(0, src_path)

import mirrorshades  # noqa: E402

mirrorshades.main()
